### PR TITLE
Adds package.json

### PR DESCRIPTION
**Pull request by dbkaplun**
Please also run `npm publish` so we can install like `npm install --save fixed-table-header`! I will be happy to update the README if you want.

### CODE REVIEW

**Comment by idavidmcdonald** [comment]
+1

**Comment by YuiSakamoto** [comment]
:+1:

**Comment by tbranyen** [comment]
I published this since I need it for a project. Once @markmalek takes over I'll transfer the package.

**Comment by markmalek** [comment]
@tbranyen I've just accepted the pull request.

**Comment by tbranyen** [comment]
@markmalek whats your npm username? I'll transfer it immediately

**Comment by markmalek** [comment]
@tbranyen thanks, my username is `markmalek`

**Comment by tbranyen** [comment]
All set @markmalek I updated it to make you the owner and removed myself. Thanks for the quick resolution!

**Pull request merged**
